version: '3.8'

services:
  cardiocare-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    volumes:
      - .:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s